
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mcp-collectdata
  namespace: mcp-server
  labels:
    app: mcp-collectdata
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mcp-collectdata
  template:
    metadata:
      labels:
        app: mcp-collectdata
    spec:
      containers:
      - name: mcp-collectdata
        image:
        ports:
        - containerPort: 8080

---
apiVersion: v1
kind: Service
metadata:
  name: mcp-collectdata-service
  namespace: mcp-server
spec:
  selector:
    app: mcp-collectdata
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: LoadBalancer