
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mcp-stock-analysis
  namespace: mcp-server
  labels:
    app: mcp-stock-analysis
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mcp-stock-analysis
  template:
    metadata:
      labels:
        app: mcp-stock-analysis
    spec:
      containers:
      - name: mcp-stock-analysis
        image:
        ports:
        - containerPort: 8080

---
apiVersion: v1
kind: Service
metadata:
  name: mcp-stock-analysis-service
  namespace: mcp-server
spec:
  selector:
    app: mcp-stock-analysis
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: LoadBalancer